server:
  port: 8080

spring:
  application:
    name: phm-gateway

  management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://httpbin.org  # 先用一个测试网站
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1